### ISSUE TITLE
add swatches and symbols functionality

### ISSUE THREAD

**Issue by yuempark** [yuempark/pystrat#5]

**Comment by duserzym** [comment]
@williamjsdavis 
if you have an idea about adding the USGS swatches to the stratigraphy plots, please help! 

The swatches files are here: https://pubs.usgs.gov/tm/2006/11A02/

Here is an instruction on how to use these swatch files in illustrator: https://blogs.otago.ac.nz/si-geology/resources/illustrationgraphics-resources/usgs-ai-pack-instructions-and-download-link/

Here is an example of a figure that I am working on. Currently Pystrat output looks like this: 
![Screenshot 2023-05-21 at 16 28 09](https://github.com/yuempark/pystrat/assets/39976081/411cb336-fd2b-43a8-b27d-2bfaa318a3cf)

I would like to add the patterns in Pystrat so that it would look like this:
![Screenshot 2023-05-21 at 16 28 48](https://github.com/yuempark/pystrat/assets/39976081/f6f3c34a-6892-4df0-8a15-2f5a15afa8d0)

Thanks!
Yiming

**Comment by sarttiso** [comment]
Swatches and annotations are now possible with #9
